spring:
  application:
    name: eurekaserver
  ## this may be needed to run locally
  #config:
  #  import: configserver:http://configserver:8071

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true