services:
  accounts:
    image: "nishantsnaik/accounts:s2"
    container_name: accounts-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vybercoders
  loans:
    image: "nishantsnaik/loans:s2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vybercoders
  cards:
    image: "nishantsnaik/cards:s2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vybercoders
networks:
  vybercoders:
    driver: "bridge"